# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests and deploy

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.9"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        python -m pip install pytest     
    - name: Run tests
      run: | 
        python -m pytest -r CD/
    - name: Check test results
      run: |
        if [ $? -eq 0 ]; then
          echo "Tests passed, proceeding with deployment"
        else
          echo "Tests failed, skipping deployment"
          exit 1
        fi
    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
    - name: Clone repository
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} ssh root@206.189.104.96 "git clone git@github.com:BAA2001/CD.git /home/CD"
    - name: Deploy code
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} ssh root@206.189.104.96 "cd /home/CD && git pull origin master" 